## Numpay Array and Basics

In [3]:
print("Hello")

Hello


In [4]:
import numpy as np

# Creating array from list

In [5]:
arr_1d = np.array([1, 2,3])
print("1D array : ",arr_1d)

arr_2d = np.array([[1,2,3], [4, 5, 6]])
print("2d array : ", arr_2d)

1D array :  [1 2 3]
2d array :  [[1 2 3]
 [4 5 6]]


## List vs numpy array 


In [ ]:
list1 = [1, 2, 3]
print("Pthon list multiplication : ", list1 * 2)

np_array = np.array([1, 2, 3])
print("Numpy array multiplication : ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("List operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(10000000) * 2 
print("Numpy operation time : ", time.time() - start)

Pthon list multiplication :  [1, 2, 3, 1, 2, 3]
Numpy array multiplication :  [2 4 6]
List operation time :  0.9914062023162842
Numpy operation time :  0.04660201072692871


## Creating array from scratch

In [19]:
zeros = np.zeros((3, 4)) # (row, column)
print("Zero matrices : \n", zeros)

ones = np.ones((3, 4))
print("One's matrices : \n", ones)

full = np.full((3, 4), 7)
print("Full matrices of value 7 is : \n", full)

random = np.random.random((2, 3)) # random values between 0 and 1
print("Random matrix : ", random)

sequence = np.arange(0, 11, 1) # arnage(start, stop, step) *stop exclusive
print("Sequence matrix : ", sequence)



Zero matrices : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One's matrices : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full matrices of value 7 is : 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random matrix :  [[0.55278128 0.4628809  0.94262159]
 [0.75354825 0.78843857 0.4167911 ]]
Sequence matrix :  [ 0  1  2  3  4  5  6  7  8  9 10]


## Vector , Matrix and Tensor

In [30]:
vector = np.array([1, 2, 3]) # 1d array
print("Vector : ", vector)

matrix = np.array([[1, 2, 3],  # 2d array
                   [4, 5, 6]])
print("Matrix : \n", matrix)
print("Matrix Dimension : ", matrix.ndim)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5,6], [7,8]]])
print("Tensor: \n", tensor)
print("This Tensor Shape : ", tensor.shape)
print("Tensor Dimension : ", tensor.ndim)

Vector :  [1 2 3]
Matrix : 
 [[1 2 3]
 [4 5 6]]
Matrix Dimension :  2
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
This Tensor Shape :  (2, 2, 2)
Tensor Dimension :  3


## Array Properties


In [35]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size : ", arr.size) # total number of elements
print("Data Type : ", arr.dtype) # data type

Shape :  (2, 3)
Dimension :  2
Size :  6
Data Type :  int64


## Aray Reshapped

In [49]:
arr = np.arange(12)
print("Original array : ", arr)

reshaped = arr.reshape((3, 4)) # you can not reshaped to a n-dimentional array which have less or many of the number of items in original
print("Reshaped array : \n", reshaped)

flattened = reshaped.flatten()
print("Flattened version of the reshaped array is : ", flattened)

raveled = reshaped.ravel() # return view instead of copy
print("Raveled version of the reshapped array is : ", raveled)

# Transpose
transpose = reshaped.T
print("Transpose matrix of : \n", reshaped, " \nis : \n", transpose)

Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened version of the reshaped array is :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled version of the reshapped array is :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose matrix of : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]  
is : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
