In [1]:
import numpy as np

## Slice in Numpy

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array : ", arr)
print("Basic Slicing : ", arr[2: 7])
print("With step : ", arr[1:8:2])
print("Negative indexing : ", arr[-4])

Original array :  [ 1  2  3  4  5  6  7  8  9 10]
Basic Slicing :  [3 4 5 6 7]
With step :  [2 4 6 8]
Negative indexing :  7


## Access in 2d Array


In [3]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Dimension of array : ", arr_2d.ndim)
print("Access a specif element : ", arr_2d[1, 2])
print("Entire row : ", arr_2d[1])
print("Entire column : ", arr_2d[:, 1])

Dimension of array :  2
Access a specif element :  6
Entire row :  [4 5 6]
Entire column :  [2 5 8]


## Sorting


In [4]:
unsortedArray = np.array([12, 10, 12, 11, 15, 3, 5, 1, 90, 12, 37])
print("Unsorted 1d-array : ", unsortedArray)
print("Sorted 1d-array : ", np.sort(unsortedArray))

print()

unsortedArray_2d = np.array([[3, 8, 5],
                             [9, 6, 3],
                             [4, 1, 7]])
print("Orginal 2d-array unsorted : \n", unsortedArray_2d)
print("Sorted 2d-arrray by column : \n", np.sort(unsortedArray_2d, axis=0))
print("Sorted 2d-arrray by row : \n", np.sort(unsortedArray_2d, axis=1))

Unsorted 1d-array :  [12 10 12 11 15  3  5  1 90 12 37]
Sorted 1d-array :  [ 1  3  5 10 11 12 12 12 15 37 90]

Orginal 2d-array unsorted : 
 [[3 8 5]
 [9 6 3]
 [4 1 7]]
Sorted 2d-arrray by column : 
 [[3 1 3]
 [4 6 5]
 [9 8 7]]
Sorted 2d-arrray by row : 
 [[3 5 8]
 [3 6 9]
 [1 4 7]]


## Filter


In [5]:
numbers = np.arange(1, 11)
print("Original array : ",numbers)
evenNumbers = numbers[numbers % 2 == 0] # we can give expression in numpy array
print("Even numbers array : ", evenNumbers)

# with mask
mask = numbers > 5
print("Numbers greater than 5 : ", numbers[mask])
print("Numbers less than 5 : ", numbers[numbers < 5])


Original array :  [ 1  2  3  4  5  6  7  8  9 10]
Even numbers array :  [ 2  4  6  8 10]
Numbers greater than 5 :  [ 6  7  8  9 10]
Numbers less than 5 :  [1 2 3 4]


## Indexing


In [6]:
numbers = np.array([10, 20, 1, 2, 4, 8, 7, 3])
print("Origina array : ", numbers)

indices = [0, 2, 5]
print(f"Get values by indices({indices}) list : ", numbers[indices])

# where indexing
where_indices = np.where(numbers > 5)
print("The indices of elements which are greater than 5 : ", where_indices)
print("Values greater than 5 by where indices : ", numbers[where_indices])

# condition array
condition_array = np.where(numbers > 5, numbers * 4, numbers)
print("Condition array : ", condition_array) # it prints all array elements by modifying its value based on condition , here if element is grater than 5 it value has been modified to value*4 else no value update just print as it is


Origina array :  [10 20  1  2  4  8  7  3]
Get values by indices([0, 2, 5]) list :  [10  1  8]
The indices of elements which are greater than 5 :  (array([0, 1, 5, 6]),)
Values greater than 5 by where indices :  [10 20  8  7]
Condition array :  [40 80  1  2  4 32 28  3]


## Adding and Removing Data

In [7]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

combinedArray = arr1 + arr2 # it add two same index value and store them , length of two array must be same otherwise it gives error
print("Add two array using '+' :  ", combinedArray) # 

combinedArray = np.concatenate((arr1, arr2))
print("Combinad array is : ", combinedArray)

# add new row to 2d-arrray
original = np.array([[1, 2, 3], [4, 5, 6]])
newRow = np.array([7, 8, 9])

withNewRow = np.vstack((original, newRow))
print("The array with new added row : \n",withNewRow)

newCol = np.array([ [100] , [200] ])
withNewCol = np.hstack((original, newCol)) 
print("The array with new added column : \n", withNewCol)

# remove element from array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
deleted = np.delete(arr, 2) # syntex : np.delete(array_Name, index) -> returns array without the deleted element
print("Array after removing element : ", deleted)
print("Original array after deletion : ", arr) # Original array will not change

Add two array using '+' :   [11 22 33 44]
Combinad array is :  [ 1  2  3  4 10 20 30 40]
The array with new added row : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The array with new added column : 
 [[  1   2   3 100]
 [  4   5   6 200]]
Array after removing element :  [1 2 4 5 6 7]
Original array after deletion :  [1 2 3 4 5 6 7]


## Compatibility check

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = np.array([100, 200, 300, 400])

print("Compatibility check : ", a.shape == b.shape)

Compatibility check :  True
